### ISSUE TITLE
"Failed to download last build"

### ISSUE THREAD

**Issue by NaleC3D** [Fedoraware/Fedoraloader-Legacy#40]
Guys, every time I use Fedoraloader when tf2 opens I get an error saying "Failed to download last build" how fix it?

**Comment by SylveonBottle** [comment]
https://nightly.link might be down. Check if you can access the following:
https://nightly.link/Fedoraware/Fedoraware/workflows/msbuild/main/Fedoraware.zip

If the site's down, you'll just have to wait for it to come back online. If you're getting an SSL error, it may be due to your system clock being horribly incorrect, or the site's web admins forgot to update the SSL certificate for this month. 

A temporary fix to this is to download fedoraware from the latest [Actions page](https://github.com/Fedoraware/Fedoraware/actions?query=branch%3Amain) and place into your TEMP folder. I'm unsure of the exact folder locations or steps to do this.

Another temporary solution is to use Fedoraware to inject the steam bypass, and then use Xenos or a similar injector to manually inject fedoraware.

**Comment by NaleC3D** [comment]
Exactly why i need paste in temp?, and i cant acces to the pages

**Comment by lnx00** [comment]
nightly.link is up again
